version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npm install selenium-side-runner
      - run: selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars,headless]" TEST2.side    
#      - run: npm install typescript@3.7.2
#      - sonarcloud/scan
#      - run:
#          command: |
#            STATUS=$(curl -u "${SONAR_TOKEN}:" https://sonarcloud.io/api/qualitygates/project_status?projectKey=kura2020_public2 | jq -r '.projectStatus.status')
#            echo "Status of SonarQube task is ${STATUS} "
#            if [ "${STATUS}" != "OK" ]; then
#                echo "Quality gate is not OK - exiting with error"
#                # exit 1
#            fi
workflows:
    build-and-test:
      jobs:
        - build-and-test:
            context: sonarcloud
