version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install typescript
      - sonarcloud/scan
      - run:
          command: |
            STATUS=$(curl -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=kura2020_public2&branch=${CIRCLE_BRANCH}" | jq -r '.projectStatus.status')
            echo "Status of SonarQube task is ${STATUS} "
            if [ "${STATUS}" != "OK" ]; then
                echo "Quality gate is not OK - exiting with error"
                # exit 1
            fi
workflows:
    build-and-test:
      jobs:
        - build-and-test:
            context: sonarcloud
